### PR TITLE
only download selected file type

### PR DESCRIPTION
**Pull request by mhinsch**
A quick fix to enable selection of file type to download. Especially with comic books downloading *everything* is a bit annoying.

### CODE REVIEW

**Comment by niemannd** [comment]
As i dont have a comic book bundle i really appreciate this PR. 
There are two things i would change. 
1) add a option to download all available filetypes. This way we dont lose the "dowload all" functionality. 
2) rename the button "download selected filetype(s)" or something along those lines. Makes it a bit more clear what we download.
Thanks 👍

**Comment by mhinsch** [comment]
done

**Comment by niemannd** [comment]
Update is live, thanks for your work.

**Comment by mhinsch** [comment]
Thanks!

**Pull request merged**
